### ISSUE TITLE
Text background not updating after toggling tree view

### ISSUE THREAD

**Issue by adifaidz** [camel-chased/editor-background#27]
The text background stays at the previous location instead of updating towards the new one.

![image](https://cloud.githubusercontent.com/assets/12843519/19013742/5ddb906e-880c-11e6-83f0-e707899042aa.png)

**Comment by swthate** [comment]
I'm having a somewhat similar issue.

However, instead of my text background shifting to the right, after a few lines of working fine, they shift down a few lines. I'm experiencing this on HTML, PHP, SVG and Twig files. So far it looks like SCSS files are working normally.

btw, @adifaidz what is the syntax theme you're using and the background image? I really like that combo! :)

**Comment by adifaidz** [comment]
[Duotone Dark Sea](https://atom.io/themes/duotone-dark-sea-syntax) for syntax.

The background is an image from a game called firewatch :
https://wall.alphacoders.com/by_sub_category.php?id=228280

For official firewatch wallpapers : 
http://blog.camposanto.com/post/138965082204/firewatch-launch-wallpaper-when-we-redid-the

Cheers, 😉

**Comment by camel-chased** [comment]
should be fixed now, thanks
